### ISSUE TITLE
Support for Teams incoming web hook

### ISSUE THREAD

**Issue by michaelaubertcmc** [JakeWharton/dependency-watch#154]
Inspired by the newly released support for Slack notifications (without using IFTTT)

We can make simple Teams action cards
![Screenshot 2024-02-05 at 12 03 22](https://github.com/JakeWharton/dependency-watch/assets/133359197/68e73065-b850-4030-8957-b1bd45fc750e)

I have deployed an on-premise container with these changes already. it would make a small PR.

**Comment by JakeWharton** [comment]
I don't use teams, so a PR would be welcome if you want support.

**Comment by michaelaubertcmc** [comment]
Let's try https://github.com/JakeWharton/dependency-watch/pull/155
