### ISSUE TITLE
Support HTTP proxy

### ISSUE THREAD

**Issue by michaelaubertcmc** [JakeWharton/dependency-watch#156]
There seems to be two parts to making dependency-watch work well inside networks that require the use of a proxy:

1 - Downloading the Gradle distribution when building the container

That can solved by copying a gradle.properties if it exists, using Docker COPY globbing e.g.

```
- COPY gradlew settings.gradle .editorconfig ./
+ COPY gradlew settings.gradle .editorconfig gradle.propertie[s] ./
```

2 - OkHttp requests to maven repositories when running the container

`main.kt` contains the only `OkHttpClient.Builder().build()` and we could check `System.getenv("https_proxy")` to configure OkHttp connections.

I have deployed both of these in a network that needed them so I can make a PR for both.
It would give us the ability to build and run the container in corporate networks without needing to fork the project.

**Comment by JakeWharton** [comment]
Both sound good to me
