### ISSUE TITLE
Release to SDKMan

### ISSUE THREAD

**Issue by eygraber** [JakeWharton/dependency-watch#167]
Any interest in having this released to [SDKMan](https://sdkman.io/vendors)?

**Comment by JakeWharton** [comment]
I do not use it, so I don't want to maintain it. Anyone else is free too, however.

**Comment by eygraber** [comment]
I'm happy to maintain it. I think as the repo owner you need to make the initial request for API keys and add them to secrets, but I can do all the legwork until that point if you're ok with that.

**Comment by JakeWharton** [comment]
I think you could do it as a separate repo using a cron-based GitHub Action that checked for new releases of the tool and then hit their API or whatever they want to inform them of updates. I don't want to have a direct integration which implies I endorse the SDKMAN's use, or that people seeking help with the integration should come here and file issues.
